image: haskell:8.10.7

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache: &global_cache
  paths:
    - .stack
    - .stack-work
    - target

before_script:
  - stack config set system-ghc --global true

build:
  stage: build
  script:
    - rm -rf .stack-work/install/*/*/*/bin
    - stack build --no-terminal --coverage --test --bench --no-run-tests --no-run-benchmarks
  after_script:
    - rm -rf ./bin
    - mv .stack-work/install/*/*/*/bin ./bin
  artifacts:
    paths:
      - "bin/"

test:
  stage: test
  script:
    - apt-get update -yqq
    - apt-get install -y --no-install-recommends graphviz dot2tex libtinfo5 texlive-latex-base poppler-utils preview-latex-style texlive-pstricks poppler-utils
    - rm -rf .stack-work/install/*/*/*/hpc
    - stack --no-terminal test --coverage smcdel:test:examples smcdel:test:k smcdel:test:translations
  coverage: '/(\d+)% top-level declarations used/'
  after_script:
    - rm -rf ./hpc
    - mv .stack-work/install/*/*/*/hpc ./hpc
  artifacts:
    when: always
    paths:
      - "hpc/"
  cache:
    <<: *global_cache
    policy: pull

test-web:
  stage: test
  script:
    - apt-get update -yqq
    - apt-get install -y --no-install-recommends graphviz dot2tex libtinfo5 texlive-latex-base poppler-utils preview-latex-style texlive-pstricks wget firefox-esr openjdk-11-jre-headless
    - stack --no-terminal test smcdel:exe:smcdel-web smcdel:test:web
  cache:
    <<: *global_cache
    policy: pull

test-CUDD:
  stage: test
  script:
    - rm -rf .stack-work/install/*/*/*/hpc
    - stack --no-terminal test --coverage smcdel:test:CUDD
  coverage: '/(\d+)% top-level declarations used/'
  after_script:
    - rm -rf ./hpc
    - mv .stack-work/install/*/*/*/hpc ./hpc
  allow_failure: true
  artifacts:
    when: always
    paths:
      - "hpc/"
  cache:
    <<: *global_cache
    policy: pull

hlint:
  stage: test
  before_script:
  script:
    - curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
  cache:
